// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Simple Inventory API
This is a simple API


    Schemes:
      https
    Host: virtserver.swaggerhub.com
    BasePath: /nxmmob/helloworld/1.0.0
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <you@your-company.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
