# coding: utf-8

"""
    Simple Inventory API

    This is a simple API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Manufacturer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'home_page': 'str',
        'phone': 'str'
    }

    attribute_map = {
        'name': 'name',
        'home_page': 'homePage',
        'phone': 'phone'
    }

    def __init__(self, name=None, home_page=None, phone=None):  # noqa: E501
        """Manufacturer - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._home_page = None
        self._phone = None
        self.discriminator = None

        self.name = name
        if home_page is not None:
            self.home_page = home_page
        if phone is not None:
            self.phone = phone

    @property
    def name(self):
        """Gets the name of this Manufacturer.  # noqa: E501


        :return: The name of this Manufacturer.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Manufacturer.


        :param name: The name of this Manufacturer.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def home_page(self):
        """Gets the home_page of this Manufacturer.  # noqa: E501


        :return: The home_page of this Manufacturer.  # noqa: E501
        :rtype: str
        """
        return self._home_page

    @home_page.setter
    def home_page(self, home_page):
        """Sets the home_page of this Manufacturer.


        :param home_page: The home_page of this Manufacturer.  # noqa: E501
        :type: str
        """

        self._home_page = home_page

    @property
    def phone(self):
        """Gets the phone of this Manufacturer.  # noqa: E501


        :return: The phone of this Manufacturer.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this Manufacturer.


        :param phone: The phone of this Manufacturer.  # noqa: E501
        :type: str
        """

        self._phone = phone

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Manufacturer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
