// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AddReply struct {
	_tab flatbuffers.Table
}

func GetRootAsAddReply(buf []byte, offset flatbuffers.UOffsetT) *AddReply {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AddReply{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AddReply) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AddReply) Table() flatbuffers.Table {
	return rcv._tab
}

func AddReplyStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func AddReplyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
