// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

type DoneFilter = int32
const (
	DoneFilterNONE DoneFilter = 0
	DoneFilterDONE DoneFilter = 1
	DoneFilterNOT_DONE DoneFilter = 2
)

var EnumNamesDoneFilter = map[DoneFilter]string{
	DoneFilterNONE:"NONE",
	DoneFilterDONE:"DONE",
	DoneFilterNOT_DONE:"NOT_DONE",
}

