// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DoneRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsDoneRequest(buf []byte, offset flatbuffers.UOffsetT) *DoneRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DoneRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DoneRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DoneRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DoneRequest) Index() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DoneRequest) MutateIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func DoneRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DoneRequestAddIndex(builder *flatbuffers.Builder, index int32) {
	builder.PrependInt32Slot(0, index, 0)
}
func DoneRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
