// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DoneReply struct {
	_tab flatbuffers.Table
}

func GetRootAsDoneReply(buf []byte, offset flatbuffers.UOffsetT) *DoneReply {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DoneReply{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DoneReply) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DoneReply) Table() flatbuffers.Table {
	return rcv._tab
}

func DoneReplyStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func DoneReplyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
