// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ListReply struct {
	_tab flatbuffers.Table
}

func GetRootAsListReply(buf []byte, offset flatbuffers.UOffsetT) *ListReply {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ListReply{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ListReply) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ListReply) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ListReply) Tasks(obj *Task, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ListReply) TasksLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ListReplyStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ListReplyAddTasks(builder *flatbuffers.Builder, tasks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(tasks), 0)
}
func ListReplyStartTasksVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ListReplyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
