// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddInventoryCreatedCode is the HTTP code returned for type AddInventoryCreated
const AddInventoryCreatedCode int = 201

/*AddInventoryCreated item created

swagger:response addInventoryCreated
*/
type AddInventoryCreated struct {
}

// NewAddInventoryCreated creates AddInventoryCreated with default headers values
func NewAddInventoryCreated() *AddInventoryCreated {

	return &AddInventoryCreated{}
}

// WriteResponse to the client
func (o *AddInventoryCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddInventoryBadRequestCode is the HTTP code returned for type AddInventoryBadRequest
const AddInventoryBadRequestCode int = 400

/*AddInventoryBadRequest invalid input, object invalid

swagger:response addInventoryBadRequest
*/
type AddInventoryBadRequest struct {
}

// NewAddInventoryBadRequest creates AddInventoryBadRequest with default headers values
func NewAddInventoryBadRequest() *AddInventoryBadRequest {

	return &AddInventoryBadRequest{}
}

// WriteResponse to the client
func (o *AddInventoryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddInventoryConflictCode is the HTTP code returned for type AddInventoryConflict
const AddInventoryConflictCode int = 409

/*AddInventoryConflict an existing item already exists

swagger:response addInventoryConflict
*/
type AddInventoryConflict struct {
}

// NewAddInventoryConflict creates AddInventoryConflict with default headers values
func NewAddInventoryConflict() *AddInventoryConflict {

	return &AddInventoryConflict{}
}

// WriteResponse to the client
func (o *AddInventoryConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
